# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KAPUj-y8tX4qArzHF2QeL9BTot1G9YCl
"""

import pandas as pd
import re

def add_virtual_column(df: pd.DataFrame, role: str, new_column: str) -> pd.DataFrame:

    valid_label = r"^[A-Za-z_]+$"

    if not re.fullmatch(valid_label, new_column):
        return pd.DataFrame([])

    for col in df.columns:
        if not re.fullmatch(valid_label, col):
            return pd.DataFrame([])

    role = role.strip()

    match = re.fullmatch(r"\s*([A-Za-z_]+)\s*([\+\-\*])\s*([A-Za-z_]+)\s*", role)

    if not match:
        return pd.DataFrame([])

    col1, operator, col2 = match.groups()

    if col1 not in df.columns or col2 not in df.columns:
        return pd.DataFrame([])

    result = df.copy()

    if operator == "+":
        result[new_column] = result[col1] + result[col2]
    elif operator == "-":
        result[new_column] = result[col1] - result[col2]
    elif operator == "*":
        result[new_column] = result[col1] * result[col2]

    return result